"""
flu/utils/verification.py
=========================
Common invariant checks that operate on plain numpy arrays.

Single Responsibility: verify mathematical invariants, return
structured result dicts.  No construction logic here.

All functions are pure (no side-effects) and accept arrays by value,
so they can be reused across core, container, and test layers.
"""

from __future__ import annotations

from typing import Any, Dict, List, Tuple

import numpy as np

from flu.utils.math_helpers import digits_signed, digits_unsigned, mean_of_digits


# ── Latin-property check ──────────────────────────────────────────────────────

def check_latin(array: np.ndarray, n: int, signed: bool = True) -> Dict[str, Any]:
    """
    Verify the Latin Hypercube property for every axis-aligned 1-D slice.

    THEOREM (Latin Property, STATUS: PROVEN for FM-Dance generated arrays):
        For an n^d hyperprism M generated by FM-Dance or kinetic recombination,
        every 1-D slice M[i₁, …, :, …, i_d] is a permutation of the digit set D.

    PROOF SKETCH:
        M[i₁,…,i_d] = ⊕_k π_k[i_k].
        Fix all indices except axis a.  The a-th term π_a[i_a] ranges over all of
        D as i_a varies (since π_a is a permutation).  The sum with the fixed
        partial sum shifts values bijectively, so the slice is still a permutation of D.

    Parameters
    ----------
    array  : np.ndarray  shape (n,)*d
    n      : int
    signed : bool

    Returns
    -------
    dict with keys: latin_ok (bool), violations (list of axis, fixed_idx tuples)
    """
    d = array.ndim
    digits = set(digits_signed(n) if signed else digits_unsigned(n))
    violations: List[Tuple] = []
    latin_ok = True

    for axis in range(d):
        other_axes = [i for i in range(d) if i != axis]
        for fixed in np.ndindex(*[n] * len(other_axes)):
            idx: List[Any] = []
            fi = 0
            for dim in range(d):
                if dim == axis:
                    idx.append(slice(None))
                else:
                    idx.append(fixed[fi])
                    fi += 1
            projection = set(int(v) for v in array[tuple(idx)].flatten())
            if projection != digits:
                latin_ok = False
                violations.append((axis, fixed))
                if len(violations) >= 10:   # cap to avoid huge output
                    return {"latin_ok": False, "violations": violations}

    return {"latin_ok": latin_ok, "violations": violations}


# ── Mean-centering check ──────────────────────────────────────────────────────

def check_mean_centered(array: np.ndarray, n: int, d: int,
                         signed: bool = True, atol: float = 1e-10) -> Dict[str, Any]:
    """
    Verify that the overall mean of the hyperprism matches the theoretical value.

    STATUS: PROVEN (odd signed n → mean = 0; even or unsigned → bounded shift).

    For signed odd n the expected global mean is exactly 0.
    For signed even n the expected mean is 0.5 (near-symmetric set).
    For unsigned n the expected mean is (n-1)/2.
    """
    expected = mean_of_digits(n, signed)
    actual   = float(np.mean(array))
    ok       = bool(np.isclose(actual, expected, atol=atol))
    return {"mean_ok": ok, "actual": actual, "expected": expected, "atol": atol}


# ── Coverage check ────────────────────────────────────────────────────────────

def check_coverage(array: np.ndarray, n: int, d: int,
                    signed: bool = True) -> Dict[str, Any]:
    """
    Verify that every value in the digit set appears exactly n^{d-1} times.

    For a Latin hypercube of shape (n,)*d, each digit must appear
    in every axis once per (d-1)-dimensional slice, totalling n^{d-1} times
    globally.

    STATUS: PROVEN (consequence of Latin property).
    """
    digits   = digits_signed(n) if signed else digits_unsigned(n)
    flat     = array.flatten()
    expected_count = n ** (d - 1)
    violations: Dict[int, int] = {}

    for dv in digits:
        count = int(np.sum(flat == dv))
        if count != expected_count:
            violations[dv] = count

    return {
        "coverage_ok": len(violations) == 0,
        "expected_count": expected_count,
        "violations": violations,
    }


# ── Round-trip bijection check ────────────────────────────────────────────────

def check_round_trip(index_to_coords_fn, coords_to_index_fn,
                     n: int, d: int) -> Dict[str, Any]:
    """
    Verify that index_to_coords and coords_to_index are mutual inverses.

    THEOREM (FM-Dance Bijection, STATUS: PROVEN by construction):
        For all k ∈ [0, n^d), coords_to_index(index_to_coords(k)) = k.

    Parameters
    ----------
    index_to_coords_fn : callable  k → tuple
    coords_to_index_fn : callable  tuple → k
    n, d               : int

    Returns
    -------
    dict with keys: bijection_ok (bool), errors (int), total (int)
    """
    total  = n ** d
    errors = 0
    for k in range(total):
        coords = index_to_coords_fn(k, n, d)
        k_back = coords_to_index_fn(coords, n, d)
        if k_back != k:
            errors += 1
    return {
        "bijection_ok": errors == 0,
        "errors": errors,
        "total": total,
    }
