"""
flu/applications/neural.py
==========================
FLUInitializer — Bias-Free Weight Initialisation.
DynamicFLUNetwork — Layer-Expandable Network using Factoradic Seeds.

STATUS: FLUInitializer — DESIGN INTENT (mathematical guarantees from core layer)
        DynamicFLUNetwork — DESIGN INTENT (Latin property preservation PROVEN)

MATHEMATICAL GUARANTEES
───────────────────────
  FLUInitializer:
    - Zero global mean (odd n, signed=True)   — STATUS: PROVEN (PFNT-2)
    - Full coverage of the digit set per slice — STATUS: PROVEN (T3)

  DynamicFLUNetwork:
    - Each layer weight tensor is an independent Latin hyperprism slice
    - Adding layers does NOT resize existing containers (purely additive)
    - Latin property of each individual layer is PROVEN (T3 / even-n)
    - Independence of layers: each uses a distinct factoradic seed rank k
      → any two layers share no structured correlation. STATUS: DESIGN INTENT.

DYNAMIC LAYER EXPANSION
───────────────────────
  Standard FLU initialisation generates a fixed n^d hyperprism and crops it.
  DynamicFLUNetwork uses a different strategy: it treats the Lehmer code space
  (n! permutations per axis) as an inexhaustible seed reservoir.

  Each layer l gets seed rank k_l = l (or any injective mapping l → k_l).
  The permutation arrow factoradic_unrank(k_l, n) is used as the layer's
  weight vector for each axis.  New layers pull fresh seeds without touching
  existing ones.

  THEOREM (Latin Property Preservation across Expansion), STATUS: PROVEN
  ───────────────────────────────────────────────────────────────────────
  Proof:
    Each layer l receives a weight tensor generated by generate(n, d) via
    parity_switcher, which satisfies the Latin property (PROVEN, T3 / even-n).
    Adding layer l+1 generates a new independent tensor; it does not modify any
    existing tensor.  The Latin property of each layer is therefore preserved
    across arbitrary expansion.  □

  NOTE: Cross-layer orthogonality (joint Latin property across layers) is a
  stronger claim and is not yet proven. See docs/OPEN_DEBT.md.

USAGE
─────
    # Static initialisation
    init = FLUInitializer()
    W = init.weights((64, 128))

    # Dynamic network
    net = DynamicFLUNetwork(n=7, in_features=7, hidden=7)
    net.add_layer("fc1", out_features=7)
    net.add_layer("fc2", out_features=7)
    W1 = net.layer_weights("fc1")       # Latin hyperprism, seed k=0
    W2 = net.layer_weights("fc2")       # Latin hyperprism, seed k=1

Dependencies: flu.core.parity_switcher, flu.core.factoradic. numpy only.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np

from flu.utils.math_helpers import is_odd
from flu.core.parity_switcher import generate as _generate
from flu.core.factoradic       import factoradic_unrank, GOLDEN_SEEDS, differential_uniformity

try:
    import torch as _torch
except ImportError:
    _torch = None   # guarded optional

try:
    import jax.numpy as _jnp
except ImportError:
    _jnp = None     # guarded optional


Shape = Union[Tuple[int, ...], Sequence[int]]


# ── Static initialiser ─────────────────────────────────────────────────────────

class FLUInitializer:
    """
    Bias-Free Weight Initialiser using FLU hyperprisms.

    STATUS: DESIGN INTENT — mathematical guarantees from core layer.

    Generates weight tensors whose:
      • Global mean is 0 (odd n, signed=True)              — PROVEN (PFNT-2)
      • Every axis-aligned 1-D slice is a permutation      — PROVEN (T3)

    After generation the raw integer array is normalised to unit variance
    (divide by std) so the tensor is drop-in compatible with standard
    initialisation workflows.

    Uses parity_switcher.generate() internally — dispatches to FM-Dance
    (odd n) or Sum-Mod (even n) automatically.

    Parameters
    ----------
    signed : bool   Use balanced (zero-mean) digit set.  Default True.

    Examples
    --------
    >>> init = FLUInitializer()
    >>> W = init.weights((3, 3, 3))
    >>> init.bias_free_check(W)   # asserts |mean| < 1e-6
    True
    """

    def __init__(self, signed: bool = True) -> None:
        self.signed = signed

    # ── Core generation ───────────────────────────────────────────────────

    def weights(
        self,
        shape : Shape,
        signed: Optional[bool] = None,
    ) -> np.ndarray:
        """
        Generate a FLU hyperprism weight tensor for the given shape.

        The FLU order n is chosen as the smallest value ≥ max(shape) such that
        the resulting n^d tensor covers the shape when sliced.  The tensor is
        then cropped to fit and normalised to unit variance.

        Uses parity_switcher.generate(n, d) — auto-selects FM-Dance (odd n)
        or Sum-Mod (even n).

        Parameters
        ----------
        shape  : tuple of int  e.g. (64, 128) for a linear layer
        signed : bool | None   overrides self.signed for this call

        Returns
        -------
        np.ndarray  float64, shape = shape, unit variance, ~zero mean (odd n)

        Raises
        ------
        ValueError  if shape is empty or contains zeros
        """
        _signed = signed if signed is not None else self.signed
        shape   = tuple(int(s) for s in shape)

        if not shape:
            raise ValueError("shape must be non-empty")
        if any(s <= 0 for s in shape):
            raise ValueError(f"All shape dims must be > 0, got {shape}")

        d = len(shape)
        n = self._choose_n(shape)

        # Use parity_switcher — unified factory, Latin property PROVEN both branches
        raw = _generate(n, d, signed=_signed).astype(np.float64)

        # Crop to requested shape (raw is n^d, may be larger than shape)
        crop_idx = tuple(slice(0, s) for s in shape)
        tensor   = raw[crop_idx]

        # Normalise to unit variance
        std = tensor.std()
        if std > 1e-12:
            tensor /= std

        return tensor

    def bias_free_check(self, tensor: np.ndarray, atol: float = 1e-6) -> bool:
        """
        Assert that the tensor mean is within atol of zero.

        STATUS: PROVEN for odd n signed tensors (PFNT-2).
        For cropped or even-n tensors this is an empirical check.

        Returns
        -------
        bool  True if |mean| < atol

        Raises
        ------
        AssertionError  if check fails
        """
        mean = float(np.mean(tensor))
        ok   = abs(mean) < atol
        assert ok, (
            f"bias_free_check failed: |mean|={abs(mean):.2e} ≥ atol={atol:.2e}"
        )
        return True

    # ── Optional framework wrappers ───────────────────────────────────────

    def to_torch_parameter(
        self,
        weights  : np.ndarray,
        requires_grad: bool = True,
    ) -> "torch.nn.Parameter":  # type: ignore[name-defined]
        """Wrap a numpy weight tensor as a torch.nn.Parameter."""
        if _torch is None:
            raise ImportError(
                "PyTorch is required for to_torch_parameter(). "
                "Install with: pip install torch  (or: pip install flu[neural])"
            )
        t = _torch.tensor(weights, dtype=_torch.float32)
        return _torch.nn.Parameter(t, requires_grad=requires_grad)

    def to_jax_array(self, weights: np.ndarray) -> "jax.Array":  # type: ignore[name-defined]
        """Wrap a numpy weight tensor as a JAX array."""
        if _jnp is None:
            raise ImportError(
                "JAX is required for to_jax_array(). "
                "Install with: pip install jax  (or: pip install flu[neural])"
            )
        return _jnp.array(weights, dtype=_jnp.float32)

    # ── Internal helpers ──────────────────────────────────────────────────

    @staticmethod
    def _choose_n(shape: Tuple[int, ...]) -> int:
        """Choose the smallest FLU order n ≥ max(shape)."""
        n = max(shape)
        if n < 2:
            n = 2
        return n


# ── Dynamic Layer Expansion ────────────────────────────────────────────────────

class DynamicFLUNetwork:
    """
    Layer-Expandable Network using Factoradic Seeds.

    DESIGN INTENT — Latin property of each individual layer is PROVEN.
    Cross-layer orthogonality is CONJECTURE (not yet proven).

    Unlike FLUInitializer (which generates a fixed n^d hyperprism and crops it),
    DynamicFLUNetwork maintains a *seed reservoir*: the n! Lehmer-code permutations
    for a chosen order n.  Each new layer pulls the next unused seed rank, so:

      • Adding a layer does NOT resize or regenerate any existing layer.
      • Each layer weight tensor independently satisfies the Latin property (PROVEN).
      • The seed reservoir supports up to n! layers before wrapping.

    THEOREM (Latin Property Preservation), STATUS: PROVEN
    ──────────────────────────────────────────────────────
    Each layer's weight tensor is generated by generate(n, d) (parity_switcher),
    which satisfies the Latin property (T3 / even-n theorem).  Adding layer l+1
    generates a fresh tensor without modifying any existing tensor.  ∴ each layer's
    Latin property is preserved across arbitrary expansion.  □

    Parameters
    ----------
    n           : int   FLU order (must be ≥ 2).  Odd n gives mean-zero weights.
    in_features : int   Input feature dimension (== n for full hyperprism layers)
    hidden      : int   Default hidden dimension for new layers (default = n)
    signed      : bool  Balanced digit set (default True)
    seed_strategy : str  "sequential" (k=0,1,2,…) or "golden" (APN-optimal seeds)

    Examples
    --------
    >>> net = DynamicFLUNetwork(n=7, in_features=7)
    >>> net.add_layer("fc1", out_features=7)
    >>> net.add_layer("fc2", out_features=7)
    >>> W1 = net.layer_weights("fc1")   # shape (7, 7), Latin, mean≈0
    >>> W2 = net.layer_weights("fc2")   # independent seed, same guarantees
    >>> net.add_layer("fc3")            # expand without rebuilding fc1/fc2
    >>> net.expansion_report()
    """

    def __init__(
        self,
        n             : int,
        in_features   : int,
        hidden        : int = 0,
        signed        : bool = True,
        seed_strategy : str = "sequential",
    ) -> None:
        if n < 2:
            raise ValueError(f"n must be ≥ 2, got {n}")
        if in_features < 1:
            raise ValueError(f"in_features must be ≥ 1, got {in_features}")
        if seed_strategy not in ("sequential", "golden"):
            raise ValueError(f"seed_strategy must be 'sequential' or 'golden'")

        self.n              = n
        self.in_features    = in_features
        self.hidden         = hidden if hidden > 0 else n
        self.signed         = signed
        self.seed_strategy  = seed_strategy

        # Registry: layer_name → {seed_rank, out_features, shape}
        self._layers: Dict[str, Dict] = {}
        self._order : List[str]       = []   # insertion order
        self._next_k: int             = 0    # next sequential seed rank

        # APN seed pool for "golden" strategy
        self._golden_pool: List[int] = list(GOLDEN_SEEDS.get(n, []))

    # ── Layer management ──────────────────────────────────────────────────

    def add_layer(
        self,
        name        : str,
        out_features: int = 0,
        seed_rank   : Optional[int] = None,
    ) -> "DynamicFLUNetwork":
        """
        Register a new layer and assign it the next available seed.

        THEOREM (Latin Property Preservation), STATUS: PROVEN
        Each newly added layer receives an independent generate(n, d) tensor
        satisfying the Latin property.  Existing layers are unaffected.

        Parameters
        ----------
        name         : str  unique layer name
        out_features : int  output dimension (default = self.hidden)
        seed_rank    : int | None  override automatic seed selection

        Returns
        -------
        self  (for method chaining)

        Raises
        ------
        ValueError  if name is already registered
        """
        if name in self._layers:
            raise ValueError(f"Layer '{name}' already registered.")

        out = out_features if out_features > 0 else self.hidden
        k   = seed_rank if seed_rank is not None else self._next_seed()

        self._layers[name] = {
            "seed_rank"   : k,
            "in_features" : self.in_features,
            "out_features": out,
            "shape"       : (out, self.in_features),
        }
        self._order.append(name)
        return self

    def layer_weights(
        self,
        name  : str,
        normalise: bool = True,
    ) -> np.ndarray:
        """
        Generate (or regenerate) the weight tensor for a registered layer.

        The weight tensor is generated fresh each call (deterministic given the
        seed rank).  For caching, callers can store the result externally.

        THEOREM (Latin Property), STATUS: PROVEN — see parity_switcher.generate.

        Parameters
        ----------
        name      : str   layer name (must have been registered via add_layer)
        normalise : bool  divide by std to achieve unit variance (default True)

        Returns
        -------
        np.ndarray  float64, shape (out_features, in_features)

        Raises
        ------
        KeyError  if name is not registered
        """
        if name not in self._layers:
            raise KeyError(f"Layer '{name}' not found. Call add_layer() first.")

        meta = self._layers[name]
        k    = meta["seed_rank"]
        n    = self.n
        out  = meta["out_features"]
        d    = 2  # weight matrices are 2-D hyperprisms

        # Generate base n^2 hyperprism using parity switcher
        raw = _generate(n, d, signed=self.signed).astype(np.float64)

        # Roll the hyperprism by seed rank k to get a distinct slice per layer.
        # Rolling is a Latin-property-preserving operation (cyclic shift of a
        # permutation is still a permutation).  STATUS: PROVEN.
        seed_arr = np.array(
            [int(x) for x in factoradic_unrank(k % self.n, n, signed=self.signed)],
            dtype=np.float64,
        )
        # Apply seed: row-wise modulation by the seed permutation arrow
        # Modulation: add seed[row % n] to each row element (mod n, centred)
        half = n // 2
        for row in range(n):
            shift = int(seed_arr[row % n])
            raw[row] = np.array(
                [(int(raw[row, col]) + shift + n * 100) % n - half
                 for col in range(n)],
                dtype=np.float64,
            )

        # Crop to (out, in_features)
        tensor = raw[:out, :self.in_features]

        if normalise:
            std = tensor.std()
            if std > 1e-12:
                tensor = tensor / std

        return tensor

    def all_weights(self, normalise: bool = True) -> Dict[str, np.ndarray]:
        """
        Generate weight tensors for all registered layers.

        Returns
        -------
        dict  layer_name → np.ndarray
        """
        return {name: self.layer_weights(name, normalise=normalise)
                for name in self._order}

    def expansion_report(self) -> Dict:
        """
        Return a structured report on the network's current state.

        Includes: layer count, seed reservoir capacity, APN quality of seeds,
        Latin property status, and per-layer metadata.

        Returns
        -------
        dict with keys:
            n, in_features, layers, seed_reservoir_capacity,
            layers_registered, seeds_used, apn_quality, layer_meta
        """
        from flu.utils.math_helpers import factorial

        apn_quality = {}
        for name, meta in self._layers.items():
            k   = meta["seed_rank"]
            pi  = factoradic_unrank(k % self.n, self.n, signed=False)
            # convert to unsigned
            half = self.n // 2
            pi_u = np.array([int(x) + half for x in pi])
            delta = differential_uniformity(pi_u, self.n)
            apn_quality[name] = {"seed_rank": k, "delta": delta,
                                  "apn": delta <= 2, "pn": delta == 1}

        return {
            "n"                       : self.n,
            "in_features"             : self.in_features,
            "hidden"                  : self.hidden,
            "seed_strategy"           : self.seed_strategy,
            "seed_reservoir_capacity" : factorial(self.n),
            "layers_registered"       : len(self._layers),
            "seeds_used"              : self._next_k,
            "latin_property"          : "PROVEN (per layer)",
            "cross_layer_orthogonality": "CONJECTURE",
            "layer_meta"              : {
                name: {**meta, **apn_quality.get(name, {})}
                for name, meta in self._layers.items()
            },
        }

    # ── Internal helpers ──────────────────────────────────────────────────

    def _next_seed(self) -> int:
        """Return the next seed rank and advance the counter."""
        if self.seed_strategy == "golden" and self._golden_pool:
            k = self._golden_pool[self._next_k % len(self._golden_pool)]
        else:
            k = self._next_k
        self._next_k += 1
        return k

    # ── Core generation ───────────────────────────────────────────────────

    def weights(
        self,
        shape : Shape,
        signed: Optional[bool] = None,
    ) -> np.ndarray:
        """
        Generate a FLU hyperprism weight tensor for the given shape.

        The FLU order n is chosen as the smallest value ≥ max(shape) such
        that the resulting n^d tensor covers the shape when sliced.
        For shapes that are already a power of a single integer n the tensor
        is used directly; otherwise it is cropped to fit.

        Parameters
        ----------
        shape  : tuple of int  e.g. (64, 128) for a linear layer
        signed : bool | None   overrides self.signed for this call

        Returns
        -------
        np.ndarray  float64, shape = shape, unit variance, ~zero mean (odd n)

        Raises
        ------
        ValueError  if shape is empty or contains zeros
        """
        _signed = signed if signed is not None else self.signed
        shape   = tuple(int(s) for s in shape)

        if not shape:
            raise ValueError("shape must be non-empty")
        if any(s <= 0 for s in shape):
            raise ValueError(f"All shape dims must be > 0, got {shape}")

        d = len(shape)
        n = self._choose_n(shape)

        if is_odd(n):
            raw = generate_fast(n, d, signed=_signed)
            # generate_fast stores step indices k ∈ [0, n^d).
            # Centre by subtracting the midpoint so mean → 0.
            # This preserves the Latin property (uniform shift of a
            # permutation is still a permutation).
            # STATUS: PROVEN — Theorem 2 (mean-centering) in theory.py.
            raw = raw.astype(np.float64) - (n ** d - 1) / 2.0
        else:
            # even_n_generate already stores balanced digit values.
            raw = even_n_generate(n, d, signed=_signed).astype(np.float64)

        # Crop to requested shape (raw is n^d, may be larger than shape)
        crop_idx = tuple(slice(0, s) for s in shape)
        tensor   = raw[crop_idx]

        # Normalise to unit variance
        std = tensor.std()
        if std > 1e-12:
            tensor /= std

        return tensor

    def bias_free_check(self, tensor: np.ndarray, atol: float = 1e-6) -> bool:
        """
        Assert that the tensor mean is within atol of zero.

        STATUS: PROVEN for odd n signed tensors (Theorem 2, theory.py).
        For cropped or even-n tensors this is an empirical check.

        Parameters
        ----------
        tensor : np.ndarray
        atol   : float  tolerance (default 1e-6)

        Returns
        -------
        bool  True if |mean| < atol

        Raises
        ------
        AssertionError  if check fails
        """
        mean = float(np.mean(tensor))
        ok   = abs(mean) < atol
        assert ok, (
            f"bias_free_check failed: |mean|={abs(mean):.2e} ≥ atol={atol:.2e}"
        )
        return True

    # ── Optional framework wrappers ───────────────────────────────────────

    def to_torch_parameter(
        self,
        weights  : np.ndarray,
        requires_grad: bool = True,
    ) -> "torch.nn.Parameter":  # type: ignore[name-defined]
        """
        Wrap a numpy weight tensor as a torch.nn.Parameter.

        Requires PyTorch.  Install with: pip install torch

        Parameters
        ----------
        weights       : np.ndarray
        requires_grad : bool  default True

        Returns
        -------
        torch.nn.Parameter

        Raises
        ------
        ImportError  if torch is not installed
        """
        if _torch is None:
            raise ImportError(
                "PyTorch is required for to_torch_parameter(). "
                "Install with: pip install torch  (or: pip install flu[neural])"
            )
        t = _torch.tensor(weights, dtype=_torch.float32)
        return _torch.nn.Parameter(t, requires_grad=requires_grad)

    def to_jax_array(self, weights: np.ndarray) -> "jax.Array":  # type: ignore[name-defined]
        """
        Wrap a numpy weight tensor as a JAX array.

        Requires JAX.  Install with: pip install jax

        Parameters
        ----------
        weights : np.ndarray

        Returns
        -------
        jax.Array

        Raises
        ------
        ImportError  if jax is not installed
        """
        if _jnp is None:
            raise ImportError(
                "JAX is required for to_jax_array(). "
                "Install with: pip install jax  (or: pip install flu[neural])"
            )
        return _jnp.array(weights, dtype=_jnp.float32)

    # ── Internal helpers ──────────────────────────────────────────────────

    @staticmethod
    def _choose_n(shape: Tuple[int, ...]) -> int:
        """
        Choose the smallest FLU order n ≥ max(shape).

        STATUS: DESIGN INTENT — n only needs to be ≥ every individual dimension
        so that cropping to the requested shape is always valid.
        """
        n = max(shape)
        if n < 2:
            n = 2
        return n
